### ISSUE TITLE
clearing the input field generates an error

### ISSUE THREAD

**Issue by jcompagner** [Eonasdan/tempus-dominus#2492]
if i clear te input field i get this exception:

core.mjs:6485 
        
       ERROR TypeError: Cannot read properties of null (reading 'constructor')
    at Function._dateTypeCheck (tempus-dominus.esm.js:1657:1)
    at Function._dateConversion (tempus-dominus.esm.js:1712:1)
    at Dates.set (tempus-dominus.esm.js:1794:1)
    at HTMLInputElement.TempusDominus._inputChangeEvent (tempus-dominus.esm.js:3090:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25475:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
    at invokeTask (zone.js:1600:1

looking at the development branch i think this is there still a problem (the code is moved but the same)

https://github.com/Eonasdan/tempus-dominus/blob/48df57c4b24de27987f3249aeb1610f01bd44196/src/js/dates.ts#L82

i think that should be an else... because if the value is null or empty then setValue shoud be called (that clears it just fine) but after it still wants to convert it and then call setValue on that again..

**Comment by jcompagner** [comment]
the same we have for setting the viewdate to null (so i don't want to show a "selected" date)

core.mjs:6485 
        
       ERROR TypeError: Cannot read properties of null (reading 'constructor')
    at Function._dateTypeCheck (tempus-dominus.esm.js:1657:1)
    at Function._dateConversion (tempus-dominus.esm.js:1712:1)
    at processKey (tempus-dominus.esm.js:1412:1)
    at tempus-dominus.esm.js:1573:1
    at Array.forEach (<anonymous>)
    at spread (tempus-dominus.esm.js:1558:1)
    at Function._mergeOptions (tempus-dominus.esm.js:1586:1)
    at TempusDominus._initializeOptions (tempus-dominus.esm.js:3315:1)
    at TempusDominus.updateOptions (tempus-dominus.esm.js:3136:1)

**Comment by Eonasdan** [comment]
Please check the dev branch
