### ISSUE TITLE
Cannot select time in Time only picker - fails with "TypeError: Target is null."

### ISSUE THREAD

**Issue by AshleighLyon** [Eonasdan/tempus-dominus#2587]
OS - Windows
Browser - Chrome, Edge, Firefox
Version - Latest beta
Stackblitz - https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-ambbqp?file=index.html

Issue - When clicking on clock icon, the time auto fills with current time and fails in console with error: "Uncaught TypeError: target is null". When you click the icon again the time options appear however you cannot change the time or hour - clicking does not open the time or minute options.

**Comment by StrangerGithuber** [comment]
All the browsers giving the error.
Maybe you get the same error as me:

```
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Collapse.hideImmediately (collapse.ts:62:12)
    at Actions.do (actions.ts:213:30)
    at actions.ts:31:20
    at event-emitter.ts:21:7
    at Array.forEach (<anonymous>)
    at EventEmitter.emit (event-emitter.ts:20:22)
    at Display.show (index.ts:231:36)
    at Display.toggle (index.ts:414:49)
    at TempusDominus.toggle (tempus-dominus.ts:94:18)
    at TempusDominus._toggleClickEvent (tempus-dominus.ts:508:10)
    ```
When trying to change time then nothing happens whatever I am clicking to plus when I just click to the icon I get that above error message.

**Comment by Eonasdan** [comment]
Yup I borked something in the last release. Sorry about that. I'm closing this one for #2590
