### ISSUE TITLE
Unable to pick time

### ISSUE THREAD

**Issue by rizalkadis** [Eonasdan/tempus-dominus#2590]
I'm using Tempus Dominus v6.0 and using Time Only pick. But recently, the code is not response when I choose time from the popup widget. The console error log is show below:-

collapse.ts:62 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Collapse.hideImmediately (collapse.ts:62:12)
    at Actions.do (actions.ts:213:30)
    at actions.ts:31:20
    at event-emitter.ts:21:7
    at Array.forEach (<anonymous>)
    at EventEmitter.emit (event-emitter.ts:20:22)
    at Display.show (index.ts:231:36)
    at Display.toggle (index.ts:414:49)
    at TempusDominus.toggle (tempus-dominus.ts:94:18)
    at TempusDominus._toggleClickEvent (tempus-dominus.ts:508:10)

anyone can help me to resolve this?

**Comment by mxhubert** [comment]
while waiting for the fix try to disable the '//year:false,' and the error will disappear unfortunately display will be modified too

**Comment by Eonasdan** [comment]
Hello, the development branch was recently updated. Please use [this stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.js) to verify your issue is resolved.

**Comment by Eonasdan** [comment]
The dev branch was merged and beta9 was published with a fix.

**Comment by mxhubert** [comment]
works! thanks!
