### ISSUE TITLE
Set value does not work

### ISSUE THREAD

**Issue by giojkd** [Eonasdan/tempus-dominus#2831]
Can't set selected date

`picker.dates.setValue(value: DateTime, index?: number) `

triggers 

`Uncaught TypeError: Cannot read properties of undefined (reading 'isBefore')`

how do I set the selected date ? 

Tried with removing min and max date from limitations but now triggers 

`Uncaught TypeError: Cannot read properties of undefined (reading 'clone')`

I've temporarily used `picker.dates.setFromInput(string)`  

which works instead

**Comment by Eonasdan** [comment]
A stackblitz example is required.

**Comment by Eonasdan** [comment]
If you provide a SB example, I will reopen this to look at it.

**Comment by LordMike** [comment]
I'm seeing this too but I'm currently unable to follow the Stackblitz link (it fails behind the scenes, I think the link is outdated). This is with 6.7.16 from npm.

**Comment by LordMike** [comment]
There we have it.

Calling `window.datetimepicker1.dates.setValue(new Date('2023-10-24'))` throws one of the two errors - either missing `isBefore` or `clone`.

```html
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            crossorigin="anonymous"
    ></script>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/js/solid.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/js/fontawesome.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.7.16/dist/js/tempus-dominus.js"></script>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.7.16/dist/css/tempus-dominus.css"/>
</head>

<body>
<div class="container">
    <div class="alert alert-info" id="info"></div>
    <div class="row">
        <div class="col-sm-6">
            <label for="datetimepicker1Input" class="form-label"
            >Simple picker</label
            >
            <div
                    class="input-group"
                    id="datetimepicker1"
                    data-td-target-input="nearest"
                    data-td-target-toggle="nearest"
            >
                <input
                        id="datetimepicker1Input"
                        type="text"
                        class="form-control"
                        data-td-target="#datetimepicker1"
                        value="2020-11-27 15:11:57"
                />
                <span
                        class="input-group-text"
                        data-td-target="#datetimepicker1"
                        data-td-toggle="datetimepicker"
                >
              <span class="fa-solid fa-calendar"></span>
            </span>
            </div>
        </div>
    </div>
</div>

<script>
    var tdOptions = {
        // Without restrictions below, `window.datetimepicker1.dates.setValue(new Date('2023-10-24'))` throws this:
        // Uncaught TypeError: Cannot read properties of undefined (reading 'clone')
        //   at onUpdate (dates.ts:225:54)
        //   at Dates.setValue (dates.ts:244:7)
        //   at <anonymous>:1:30

        // With restrictions below, `window.datetimepicker1.dates.setValue(new Date('2023-10-24'))` throws this:
        // Uncaught TypeError: Cannot read properties of undefined (reading 'clone')
        //   at onUpdate (dates.ts:225:54)
        //   at Dates.setValue (dates.ts:244:7)
        //   at <anonymous>:1:30
        restrictions: {
            minDate: new Date('2023-10-20'),
            maxDate: new Date('2023-10-30')
        },
        localization: {
            format: 'yyyy-MM-dd HH:mm:ss',
        },
        display: {
            theme: 'auto'
        }
    };

    //using "window" is just for the stackblitz, you do not need to do this
    window.datetimepicker1 = new tempusDominus.TempusDominus(
        document.getElementById('datetimepicker1'),
        tdOptions
    );

    document.getElementById(
        'info'
    ).innerHTML = `Your browser's locale is ${navigator.language}.<br/>
	You are using version ${tempusDominus.version}`;

</script>
</body>
</html>
```

**Comment by Eonasdan** [comment]
@LordMike  `setValue` requires a `DateTime` object

**Comment by JMGbaum** [comment]
Hello, I am having a similar issue in my code. It seems to stem from having a min or max value in your configuration. [Here is a stackblitz example](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-e2zuau?file=index.js) showing the error I am running into.

Seemingly unrelated, but [I cannot set the view date either](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-kqyqwn?file=index.js).
